import Head from 'next/head'
import Image from 'next/image'
import style from './Body.module.css'
import Sidebar from '../../components/sidebar/Sidebar'
import Home from '../sidebar/home.png'
import Link from 'next/link'

export default function Body({ title, titleHead, children }){
    
    
    
    return(
        <>
        <Head>
            <title>{titleHead}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={style.container}>
            <Link href={"/"} legacyBehavior className={style.linkHome}>
                <a>
                    <div className={style.linkImage}>
                        <Image src={Home} fill={true} style={{objectFit:"contain"}}/>
                    </div>
                </a>
            </Link>
            <div className={style.sidebar}>
                <Sidebar/>
            </div>
            <div className={style.fill}>
                <div className={style.title}>{title}</div>
                { children }
            </div>
        </div>
        </>
    )
}