import Head from 'next/head'
import Sidebar from '../components/sidebar/Sidebar'
import Notification from '../components/notification/Notification'
import Navigation from '../components/navigation/Navigation'
import InputOrder from '../components/form-order/Input'
import ShowProduct from '../components/show-product/ShowProduct'

import styles from '../styles/Index.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Buby Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.sidebar}>
            <Sidebar/>
        </div>
        <div className={styles.title}>
            Good Morning, <br />Sasha
        </div>
        <div className={styles.navigation}>
            <Navigation/>
        </div>
        <div className={styles.notification}>
            <Notification/>
        </div>
        <div className={styles.form}>
            <InputOrder/>
        </div>
        <div className={styles.keuangan}>
        </div>
        <div className={styles.product}>
            <ShowProduct/>
        </div>
      </main>
    </>
  )
}
